//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrerasUniversitarias
    {
        public CarrerasUniversitarias()
        {
            this.CursosPorCarreras = new HashSet<CursosPorCarreras>();
            this.Matriculas = new HashSet<Matriculas>();
            this.Matriculas1 = new HashSet<Matriculas>();
        }
    
        public int id_CarreraUniversitaria { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public int id_DireccionCarrera { get; set; }
    
        public virtual DireccionesCarreras DireccionesCarreras { get; set; }
        public virtual ICollection<CursosPorCarreras> CursosPorCarreras { get; set; }
        public virtual ICollection<Matriculas> Matriculas { get; set; }
        public virtual ICollection<Matriculas> Matriculas1 { get; set; }
    }
}
