//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public Cursos()
        {
            this.OfertasAcademicas = new HashSet<OfertasAcademicas>();
            this.CursosPorCarreras = new HashSet<CursosPorCarreras>();
        }
    
        public int id_Curso { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
    
        public virtual ICollection<OfertasAcademicas> OfertasAcademicas { get; set; }
        public virtual ICollection<CursosPorCarreras> CursosPorCarreras { get; set; }
    }
}
