//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosPorCarreras
    {
        public int id_Curso { get; set; }
        public int id_CarreraUniversitaria { get; set; }
        public Nullable<int> id_CursoRequisito { get; set; }
        public int id_CursoPorCarrera { get; set; }
    
        public virtual CarrerasUniversitarias CarrerasUniversitarias { get; set; }
        public virtual Cursos Cursos { get; set; }
    }
}
