//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesCarreras
    {
        public DireccionesCarreras()
        {
            this.CarrerasUniversitarias = new HashSet<CarrerasUniversitarias>();
        }
    
        public int id_DireccionCarrera { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public int id_Director { get; set; }
        public int id_Subdirector { get; set; }
    
        public virtual ICollection<CarrerasUniversitarias> CarrerasUniversitarias { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        public virtual Funcionarios Funcionarios1 { get; set; }
    }
}
