//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public Estudiantes()
        {
            this.Matriculas = new HashSet<Matriculas>();
            this.Matriculas1 = new HashSet<Matriculas>();
        }
    
        public int id_Estudiante { get; set; }
        public string NombreCompleto { get; set; }
        public string Cedula { get; set; }
        public int id_Provincia { get; set; }
        public int id_Canton { get; set; }
        public int id_Distrito { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public string Carne { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Matriculas> Matriculas { get; set; }
        public virtual ICollection<Matriculas> Matriculas1 { get; set; }
    }
}
