//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public Funcionarios()
        {
            this.DireccionesCarreras = new HashSet<DireccionesCarreras>();
            this.DireccionesCarreras1 = new HashSet<DireccionesCarreras>();
            this.SedesUniversitarias = new HashSet<SedesUniversitarias>();
        }
    
        public int id_Funcionario { get; set; }
        public string NombreCompleto { get; set; }
        public string Cedula { get; set; }
        public int id_Provincia { get; set; }
        public int id_Canton { get; set; }
        public int id_Distrito { get; set; }
        public System.DateTime FechaContratacion { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual ICollection<DireccionesCarreras> DireccionesCarreras { get; set; }
        public virtual ICollection<DireccionesCarreras> DireccionesCarreras1 { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<SedesUniversitarias> SedesUniversitarias { get; set; }
    }
}
