//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas
    {
        public int id_Matricula { get; set; }
        public int id_Estudiante { get; set; }
        public int id_CarreraUniversitaria { get; set; }
        public Nullable<int> id_OfertaAcademica { get; set; }
        public Nullable<int> Nota { get; set; }
        public string Estado { get; set; }
    
        public virtual CarrerasUniversitarias CarrerasUniversitarias { get; set; }
        public virtual CarrerasUniversitarias CarrerasUniversitarias1 { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Estudiantes Estudiantes1 { get; set; }
        public virtual OfertasAcademicas OfertasAcademicas { get; set; }
    }
}
