//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class gestionmatriculaEntities3 : DbContext
    {
        public gestionmatriculaEntities3()
            : base("name=gestionmatriculaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Canton> Canton { get; set; }
        public DbSet<CarrerasUniversitarias> CarrerasUniversitarias { get; set; }
        public DbSet<Cursos> Cursos { get; set; }
        public DbSet<DireccionesCarreras> DireccionesCarreras { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Estudiantes> Estudiantes { get; set; }
        public DbSet<Funcionarios> Funcionarios { get; set; }
        public DbSet<OfertasAcademicas> OfertasAcademicas { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<SedesUniversitarias> SedesUniversitarias { get; set; }
        public DbSet<tblUsuario> tblUsuario { get; set; }
        public DbSet<CursosPorCarreras> CursosPorCarreras { get; set; }
        public DbSet<CuatrimestreXSede> CuatrimestreXSede { get; set; }
        public DbSet<Matriculas> Matriculas { get; set; }
    
        public virtual int ActualizarFuncionario(Nullable<int> id_Funcionario, string nombreCompleto, string cedula, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fechaContratacion)
        {
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("id_Funcionario", id_Funcionario) :
                new ObjectParameter("id_Funcionario", typeof(int));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            var fechaContratacionParameter = fechaContratacion.HasValue ?
                new ObjectParameter("FechaContratacion", fechaContratacion) :
                new ObjectParameter("FechaContratacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarFuncionario", id_FuncionarioParameter, nombreCompletoParameter, cedulaParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fechaContratacionParameter);
        }
    
        public virtual int AgregarEstudiante(string nombreCompleto, string cedula, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fecha_Inicio)
        {
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarEstudiante", nombreCompletoParameter, cedulaParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fecha_InicioParameter);
        }
    
        public virtual int AgregarFuncionario(string nombreCompleto, string cedula, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fechaContratacion)
        {
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            var fechaContratacionParameter = fechaContratacion.HasValue ?
                new ObjectParameter("FechaContratacion", fechaContratacion) :
                new ObjectParameter("FechaContratacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarFuncionario", nombreCompletoParameter, cedulaParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fechaContratacionParameter);
        }
    
        public virtual int EliminaEstudiante(Nullable<int> id_Estudiante)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminaEstudiante", id_EstudianteParameter);
        }
    
        public virtual int EliminaFuncionario(Nullable<int> id_Funcionario)
        {
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("id_Funcionario", id_Funcionario) :
                new ObjectParameter("id_Funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminaFuncionario", id_FuncionarioParameter);
        }
    
        public virtual ObjectResult<RetornaCantones_Result> RetornaCantones(string nombre, Nullable<int> id_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantones_Result>("RetornaCantones", nombreParameter, id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<RetornaCantonesID_Result> RetornaCantonesID(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantonesID_Result>("RetornaCantonesID", id_CantonParameter);
        }
    
        public virtual ObjectResult<RetornaDistrito_Result> RetornaDistrito(string nombre, Nullable<int> id_Canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDistrito_Result>("RetornaDistrito", nombreParameter, id_CantonParameter);
        }
    
        public virtual ObjectResult<RetornaProvincias_Result> RetornaProvincias(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaProvincias_Result>("RetornaProvincias", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaEstudianteID_Result> RetornaEstudianteID(Nullable<int> id_Estudiante)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaEstudianteID_Result>("RetornaEstudianteID", id_EstudianteParameter);
        }
    
        public virtual ObjectResult<RetornaEstudiantes_Result> RetornaEstudiantes(string nombreCompleto)
        {
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaEstudiantes_Result>("RetornaEstudiantes", nombreCompletoParameter);
        }
    
        public virtual ObjectResult<RetornaEstudiantesCed_Result> RetornaEstudiantesCed(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaEstudiantesCed_Result>("RetornaEstudiantesCed", cedulaParameter);
        }
    
        public virtual ObjectResult<RetornaFuncionarioID_Result> RetornaFuncionarioID(Nullable<int> id_Funcionario)
        {
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("id_Funcionario", id_Funcionario) :
                new ObjectParameter("id_Funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaFuncionarioID_Result>("RetornaFuncionarioID", id_FuncionarioParameter);
        }
    
        public virtual ObjectResult<RetornaFuncionarios_Result> RetornaFuncionarios(string nombreCompleto)
        {
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaFuncionarios_Result>("RetornaFuncionarios", nombreCompletoParameter);
        }
    
        public virtual int ActualizarEstudiante(Nullable<int> id_Estudiante, string nombreCompleto, string cedula, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fecha_Inicio)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEstudiante", id_EstudianteParameter, nombreCompletoParameter, cedulaParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fecha_InicioParameter);
        }
    
        public virtual int ActualizarFechaCierre(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarFechaCierre", id_UsuarioParameter);
        }
    
        public virtual int EliminarCurso(Nullable<int> id_Curso)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCurso", id_CursoParameter);
        }
    
        public virtual ObjectResult<RetornaUsuarioCorreo_Result> RetornaUsuarioCorreo(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuarioCorreo_Result>("RetornaUsuarioCorreo", usuarioParameter, contrasenaParameter);
        }
    
        public virtual int AgregarUsuario(string nombreCompleto, string usuario, string tipoUsuario, string contrasena)
        {
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("NombreCompleto", nombreCompleto) :
                new ObjectParameter("NombreCompleto", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var tipoUsuarioParameter = tipoUsuario != null ?
                new ObjectParameter("TipoUsuario", tipoUsuario) :
                new ObjectParameter("TipoUsuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarUsuario", nombreCompletoParameter, usuarioParameter, tipoUsuarioParameter, contrasenaParameter);
        }
    
        public virtual int AgregarCursos(string nombre, string codigo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarCursos", nombreParameter, codigoParameter);
        }
    
        public virtual ObjectResult<RetornaCurso_Result> RetornaCurso(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCurso_Result>("RetornaCurso", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaCursoID_Result> RetornaCursoID(Nullable<int> id_Curso)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCursoID_Result>("RetornaCursoID", id_CursoParameter);
        }
    
        public virtual ObjectResult<RetornaFuncionarioCed_Result> RetornaFuncionarioCed(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaFuncionarioCed_Result>("RetornaFuncionarioCed", cedulaParameter);
        }
    
        public virtual int ActualizarCurso(Nullable<int> id_Curso, string nombre, string codigo)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarCurso", id_CursoParameter, nombreParameter, codigoParameter);
        }
    
        public virtual int AgregarDireccionesCarrera(string nombre, string codigo, Nullable<int> id_Director, Nullable<int> id_Subdirector)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("id_Director", id_Director) :
                new ObjectParameter("id_Director", typeof(int));
    
            var id_SubdirectorParameter = id_Subdirector.HasValue ?
                new ObjectParameter("id_Subdirector", id_Subdirector) :
                new ObjectParameter("id_Subdirector", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarDireccionesCarrera", nombreParameter, codigoParameter, id_DirectorParameter, id_SubdirectorParameter);
        }
    
        public virtual ObjectResult<RetornaCursoCod_Result> RetornaCursoCod(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCursoCod_Result>("RetornaCursoCod", codigoParameter);
        }
    
        public virtual int ActualizarCarrerasUniversitaria(Nullable<int> id_CarreraUniversitaria, string nombre, string codigo, Nullable<int> id_DireccionCarrera)
        {
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var id_DireccionCarreraParameter = id_DireccionCarrera.HasValue ?
                new ObjectParameter("id_DireccionCarrera", id_DireccionCarrera) :
                new ObjectParameter("id_DireccionCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarCarrerasUniversitaria", id_CarreraUniversitariaParameter, nombreParameter, codigoParameter, id_DireccionCarreraParameter);
        }
    
        public virtual int ActualizarDireccionesCarreras(Nullable<int> id_DireccionCarrera, string nombre, string codigo, Nullable<int> id_Director, Nullable<int> id_Subdirector)
        {
            var id_DireccionCarreraParameter = id_DireccionCarrera.HasValue ?
                new ObjectParameter("id_DireccionCarrera", id_DireccionCarrera) :
                new ObjectParameter("id_DireccionCarrera", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("id_Director", id_Director) :
                new ObjectParameter("id_Director", typeof(int));
    
            var id_SubdirectorParameter = id_Subdirector.HasValue ?
                new ObjectParameter("id_Subdirector", id_Subdirector) :
                new ObjectParameter("id_Subdirector", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarDireccionesCarreras", id_DireccionCarreraParameter, nombreParameter, codigoParameter, id_DirectorParameter, id_SubdirectorParameter);
        }
    
        public virtual int AgregarCarrerasUniversitarias(string nombre, string codigo, Nullable<int> id_DireccionCarrera)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var id_DireccionCarreraParameter = id_DireccionCarrera.HasValue ?
                new ObjectParameter("id_DireccionCarrera", id_DireccionCarrera) :
                new ObjectParameter("id_DireccionCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarCarrerasUniversitarias", nombreParameter, codigoParameter, id_DireccionCarreraParameter);
        }
    
        public virtual int EliminaCarrerasUniversitarias(Nullable<int> id_CarreraUniversitaria)
        {
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminaCarrerasUniversitarias", id_CarreraUniversitariaParameter);
        }
    
        public virtual int EliminaDirrecionCarrera(Nullable<int> id_DireccionCarrera)
        {
            var id_DireccionCarreraParameter = id_DireccionCarrera.HasValue ?
                new ObjectParameter("id_DireccionCarrera", id_DireccionCarrera) :
                new ObjectParameter("id_DireccionCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminaDirrecionCarrera", id_DireccionCarreraParameter);
        }
    
        public virtual int EliminaSedesUniversitarias(Nullable<int> id_SedeUniversitaria)
        {
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("id_SedeUniversitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminaSedesUniversitarias", id_SedeUniversitariaParameter);
        }
    
        public virtual ObjectResult<RetornaCarreraUniversitaria_Result> RetornaCarreraUniversitaria(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCarreraUniversitaria_Result>("RetornaCarreraUniversitaria", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaCarreraUniversitariaCod_Result> RetornaCarreraUniversitariaCod(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCarreraUniversitariaCod_Result>("RetornaCarreraUniversitariaCod", codigoParameter);
        }
    
        public virtual ObjectResult<RetornaDireccionCarrera_Result> RetornaDireccionCarrera(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDireccionCarrera_Result>("RetornaDireccionCarrera", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaDireccionCarreraCod_Result> RetornaDireccionCarreraCod(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDireccionCarreraCod_Result>("RetornaDireccionCarreraCod", codigoParameter);
        }
    
        public virtual ObjectResult<RetornaSedesUniversitarias_Result> RetornaSedesUniversitarias(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaSedesUniversitarias_Result>("RetornaSedesUniversitarias", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaSedesUniversitariasCod_Result> RetornaSedesUniversitariasCod(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaSedesUniversitariasCod_Result>("RetornaSedesUniversitariasCod", codigoParameter);
        }
    
        public virtual ObjectResult<RetornaDireccionCarreraID_Result> RetornaDireccionCarreraID(Nullable<int> id_DireccionCarrera)
        {
            var id_DireccionCarreraParameter = id_DireccionCarrera.HasValue ?
                new ObjectParameter("id_DireccionCarrera", id_DireccionCarrera) :
                new ObjectParameter("id_DireccionCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDireccionCarreraID_Result>("RetornaDireccionCarreraID", id_DireccionCarreraParameter);
        }
    
        public virtual ObjectResult<RetornaCarreraUniversitariaID_Result> RetornaCarreraUniversitariaID(Nullable<int> id_CarreraUniversitaria)
        {
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCarreraUniversitariaID_Result>("RetornaCarreraUniversitariaID", id_CarreraUniversitariaParameter);
        }
    
        public virtual ObjectResult<RetornaSedesUniversitariasID_Result> RetornaSedesUniversitariasID(Nullable<int> id_SedeUniversitaria)
        {
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("id_SedeUniversitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaSedesUniversitariasID_Result>("RetornaSedesUniversitariasID", id_SedeUniversitariaParameter);
        }
    
        public virtual int ActualizarSedesUniversitarias(Nullable<int> id_SedeUniversitaria, string nombre, string codigo, Nullable<int> id_Director, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, string direccionFisica)
        {
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("id_SedeUniversitaria", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("id_Director", id_Director) :
                new ObjectParameter("id_Director", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            var direccionFisicaParameter = direccionFisica != null ?
                new ObjectParameter("DireccionFisica", direccionFisica) :
                new ObjectParameter("DireccionFisica", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarSedesUniversitarias", id_SedeUniversitariaParameter, nombreParameter, codigoParameter, id_DirectorParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, direccionFisicaParameter);
        }
    
        public virtual int AgregarSedeUniversitaria(string nombre, string codigo, Nullable<int> id_Director, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, string direccionFisica)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("id_Director", id_Director) :
                new ObjectParameter("id_Director", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            var direccionFisicaParameter = direccionFisica != null ?
                new ObjectParameter("DireccionFisica", direccionFisica) :
                new ObjectParameter("DireccionFisica", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarSedeUniversitaria", nombreParameter, codigoParameter, id_DirectorParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, direccionFisicaParameter);
        }
    
        public virtual int AgregarCursosPorCarreras(Nullable<int> id_Curso, Nullable<int> id_CarreraUniversitaria, Nullable<int> id_CursoRequisito)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            var id_CursoRequisitoParameter = id_CursoRequisito.HasValue ?
                new ObjectParameter("id_CursoRequisito", id_CursoRequisito) :
                new ObjectParameter("id_CursoRequisito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarCursosPorCarreras", id_CursoParameter, id_CarreraUniversitariaParameter, id_CursoRequisitoParameter);
        }
    
        public virtual int ActualizarCursosPorCarrera(Nullable<int> id_CursoPorCarrera, Nullable<int> id_CursoRequisito, Nullable<int> id_CarreraUniversitaria, Nullable<int> id_Curso)
        {
            var id_CursoPorCarreraParameter = id_CursoPorCarrera.HasValue ?
                new ObjectParameter("id_CursoPorCarrera", id_CursoPorCarrera) :
                new ObjectParameter("id_CursoPorCarrera", typeof(int));
    
            var id_CursoRequisitoParameter = id_CursoRequisito.HasValue ?
                new ObjectParameter("id_CursoRequisito", id_CursoRequisito) :
                new ObjectParameter("id_CursoRequisito", typeof(int));
    
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarCursosPorCarrera", id_CursoPorCarreraParameter, id_CursoRequisitoParameter, id_CarreraUniversitariaParameter, id_CursoParameter);
        }
    
        public virtual ObjectResult<RetornaCursoPorCarrera_Result> RetornaCursoPorCarrera(Nullable<int> id_CarreraUniversitaria)
        {
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCursoPorCarrera_Result>("RetornaCursoPorCarrera", id_CarreraUniversitariaParameter);
        }
    
        public virtual ObjectResult<RetornaCursoPorCarreraID_Result> RetornaCursoPorCarreraID(Nullable<int> id_CursoPorCarrera)
        {
            var id_CursoPorCarreraParameter = id_CursoPorCarrera.HasValue ?
                new ObjectParameter("id_CursoPorCarrera", id_CursoPorCarrera) :
                new ObjectParameter("id_CursoPorCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCursoPorCarreraID_Result>("RetornaCursoPorCarreraID", id_CursoPorCarreraParameter);
        }
    
        public virtual int EliminarCursoPorCarrera(Nullable<int> id_CursoPorCarrera)
        {
            var id_CursoPorCarreraParameter = id_CursoPorCarrera.HasValue ?
                new ObjectParameter("id_CursoPorCarrera", id_CursoPorCarrera) :
                new ObjectParameter("id_CursoPorCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCursoPorCarrera", id_CursoPorCarreraParameter);
        }
    
        public virtual int AgregarCuatrimestresxSede(Nullable<int> id_SedeUniversitaria, string periodoLectivo, string ano, string estado)
        {
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("id_SedeUniversitaria", typeof(int));
    
            var periodoLectivoParameter = periodoLectivo != null ?
                new ObjectParameter("PeriodoLectivo", periodoLectivo) :
                new ObjectParameter("PeriodoLectivo", typeof(string));
    
            var anoParameter = ano != null ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarCuatrimestresxSede", id_SedeUniversitariaParameter, periodoLectivoParameter, anoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<RetornaCuatrimestreXSede_Result> RetornaCuatrimestreXSede()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCuatrimestreXSede_Result>("RetornaCuatrimestreXSede");
        }
    
        public virtual ObjectResult<RetornaCuatrimestreXSedeID_Result> RetornaCuatrimestreXSedeID(Nullable<int> id_CuatrimestreXSede)
        {
            var id_CuatrimestreXSedeParameter = id_CuatrimestreXSede.HasValue ?
                new ObjectParameter("id_CuatrimestreXSede", id_CuatrimestreXSede) :
                new ObjectParameter("id_CuatrimestreXSede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCuatrimestreXSedeID_Result>("RetornaCuatrimestreXSedeID", id_CuatrimestreXSedeParameter);
        }
    
        public virtual int AgregarOfertasAcademidas(Nullable<int> id_CuatrimestreXSede, Nullable<int> id_Curso, Nullable<int> cuposDisponibles)
        {
            var id_CuatrimestreXSedeParameter = id_CuatrimestreXSede.HasValue ?
                new ObjectParameter("id_CuatrimestreXSede", id_CuatrimestreXSede) :
                new ObjectParameter("id_CuatrimestreXSede", typeof(int));
    
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            var cuposDisponiblesParameter = cuposDisponibles.HasValue ?
                new ObjectParameter("cuposDisponibles", cuposDisponibles) :
                new ObjectParameter("cuposDisponibles", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarOfertasAcademidas", id_CuatrimestreXSedeParameter, id_CursoParameter, cuposDisponiblesParameter);
        }
    
        public virtual ObjectResult<RetornaOfertaAcademica_Result> RetornaOfertaAcademica()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaOfertaAcademica_Result>("RetornaOfertaAcademica");
        }
    
        public virtual ObjectResult<ConsultaOfertaAcademica_Result> ConsultaOfertaAcademica(Nullable<int> id_Carrera, Nullable<int> id_SedeUniversitaria, string ano, string cuatrimestre)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("Id_Carrera", id_Carrera) :
                new ObjectParameter("Id_Carrera", typeof(int));
    
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("Id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("Id_SedeUniversitaria", typeof(int));
    
            var anoParameter = ano != null ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(string));
    
            var cuatrimestreParameter = cuatrimestre != null ?
                new ObjectParameter("Cuatrimestre", cuatrimestre) :
                new ObjectParameter("Cuatrimestre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultaOfertaAcademica_Result>("ConsultaOfertaAcademica", id_CarreraParameter, id_SedeUniversitariaParameter, anoParameter, cuatrimestreParameter);
        }
    
        public virtual int AgregarMatricula(Nullable<int> id_Estudiante, Nullable<int> id_CarreraUniversitaria, Nullable<int> id_OfertaAcademica)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            var id_CarreraUniversitariaParameter = id_CarreraUniversitaria.HasValue ?
                new ObjectParameter("id_CarreraUniversitaria", id_CarreraUniversitaria) :
                new ObjectParameter("id_CarreraUniversitaria", typeof(int));
    
            var id_OfertaAcademicaParameter = id_OfertaAcademica.HasValue ?
                new ObjectParameter("id_OfertaAcademica", id_OfertaAcademica) :
                new ObjectParameter("id_OfertaAcademica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarMatricula", id_EstudianteParameter, id_CarreraUniversitariaParameter, id_OfertaAcademicaParameter);
        }
    
        public virtual ObjectResult<RetornaMatriculaIdEstudiante_Result> RetornaMatriculaIdEstudiante(Nullable<int> id_Estudiante)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaMatriculaIdEstudiante_Result>("RetornaMatriculaIdEstudiante", id_EstudianteParameter);
        }
    
        public virtual ObjectResult<RetornaNotasPorCurso_Result> RetornaNotasPorCurso(Nullable<int> id_SedeUniversitaria, string ano, string cuatrimestre, Nullable<int> id_Curso)
        {
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("id_SedeUniversitaria", typeof(int));
    
            var anoParameter = ano != null ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(string));
    
            var cuatrimestreParameter = cuatrimestre != null ?
                new ObjectParameter("Cuatrimestre", cuatrimestre) :
                new ObjectParameter("Cuatrimestre", typeof(string));
    
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaNotasPorCurso_Result>("RetornaNotasPorCurso", id_SedeUniversitariaParameter, anoParameter, cuatrimestreParameter, id_CursoParameter);
        }
    
        public virtual int ActualizaNota(Nullable<int> id_Matricula, Nullable<int> nota)
        {
            var id_MatriculaParameter = id_Matricula.HasValue ?
                new ObjectParameter("id_Matricula", id_Matricula) :
                new ObjectParameter("id_Matricula", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("Nota", nota) :
                new ObjectParameter("Nota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizaNota", id_MatriculaParameter, notaParameter);
        }
    
        public virtual ObjectResult<RetornaNotas_Result> RetornaNotas(Nullable<int> id_SedeUniversitaria, string ano, string cuatrimestre, Nullable<int> id_Curso)
        {
            var id_SedeUniversitariaParameter = id_SedeUniversitaria.HasValue ?
                new ObjectParameter("id_SedeUniversitaria", id_SedeUniversitaria) :
                new ObjectParameter("id_SedeUniversitaria", typeof(int));
    
            var anoParameter = ano != null ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(string));
    
            var cuatrimestreParameter = cuatrimestre != null ?
                new ObjectParameter("Cuatrimestre", cuatrimestre) :
                new ObjectParameter("Cuatrimestre", typeof(string));
    
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaNotas_Result>("RetornaNotas", id_SedeUniversitariaParameter, anoParameter, cuatrimestreParameter, id_CursoParameter);
        }
    
        public virtual ObjectResult<RetornaNotasPorEstudiante_Result> RetornaNotasPorEstudiante(Nullable<int> id_Estudiante)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaNotasPorEstudiante_Result>("RetornaNotasPorEstudiante", id_EstudianteParameter);
        }
    
        public virtual ObjectResult<RetornaNotasPorEstudianteFiltro_Result> RetornaNotasPorEstudianteFiltro(string cuatrimestre, Nullable<int> id_Curso, Nullable<int> id_Estudiante)
        {
            var cuatrimestreParameter = cuatrimestre != null ?
                new ObjectParameter("Cuatrimestre", cuatrimestre) :
                new ObjectParameter("Cuatrimestre", typeof(string));
    
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("id_Curso", id_Curso) :
                new ObjectParameter("id_Curso", typeof(int));
    
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("id_Estudiante", id_Estudiante) :
                new ObjectParameter("id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaNotasPorEstudianteFiltro_Result>("RetornaNotasPorEstudianteFiltro", cuatrimestreParameter, id_CursoParameter, id_EstudianteParameter);
        }
    }
}
