//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertasAcademicas
    {
        public OfertasAcademicas()
        {
            this.Matriculas = new HashSet<Matriculas>();
        }
    
        public int id_OfertaAcademica { get; set; }
        public int id_CuatrimestreXSede { get; set; }
        public int id_Curso { get; set; }
        public int cuposDisponibles { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual CuatrimestreXSede CuatrimestreXSede { get; set; }
        public virtual ICollection<Matriculas> Matriculas { get; set; }
    }
}
