//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPVl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SedesUniversitarias
    {
        public SedesUniversitarias()
        {
            this.CuatrimestreXSede = new HashSet<CuatrimestreXSede>();
        }
    
        public int id_SedeUniversitaria { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public int id_Director { get; set; }
        public int id_Provincia { get; set; }
        public int id_Canton { get; set; }
        public int id_Distrito { get; set; }
        public string DireccionFisica { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<CuatrimestreXSede> CuatrimestreXSede { get; set; }
    }
}
